[package]
name = "harfbuzz_rust"
edition = "2021"

[dependencies]
read-fonts = { version = "0.27", optional = true }
skrifa = { version = "0.29.2", optional = true }

[lib]
name = "harfbuzz_rust"
path = "lib.rs"
crate-type = ["staticlib"]

[features]
font = ["dep:read-fonts", "dep:skrifa"]

[profile.release]
strip = true
lto = "fat"
panic = "abort"
overflow-checks = false
codegen-units = 1

[profile.debugoptimized]
inherits = "release"
debug = true
codegen-units = 16
strip = false

[profile.dev]
lto = "fat"
